version: '3.1'
services:
  stats-server:
    build:
      context:
        statistic
    image:
      stat_image
    container_name:
      stat_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stat
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build:
      context:
        basic
    image:
      basic_image
    container_name:
      basic_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_NAME=basic_db
      - DB_HOST=basic
      - DB_PORT=5433
      - DB_USER=root
      - DB_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: basic_db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=basic
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
