drop table if exists public.events;

CREATE TABLE IF NOT EXISTS public.events
(
    id bigint generated by default as identity not null primary key
    , app varchar(255) NOT NULL
    , uri varchar(255) NOT NULL
    , ip varchar(255) NOT NULL
    , dt timestamp without time zone not null
);